spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/local_database
    username: local_user
    password: local_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
