services:
  postgres:
    image: postgres:16.10
    container_name: postgres_authentication_service
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_database
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
